<a href="https://colab.research.google.com/github/srijit43/Machine-Learning-Lessions/blob/main/Neural_Network_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1]

bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias

print(output)

4.8


Above we have just shown how Neural network works with 3 neurons , some weights and bias. weights + bias = parameters

In [ ]:
#Let us create a scenario  where we have 4 hidden layer nodes and 3 nodes in output  layer
inputs = [1.0,2.0,3.0,2.5]

weights1 = [0.2,0.8,-0.5,1]
weights2 = [0.5,-0.91,0.26,-0.5]
weights3 = [-0.26,-0.27,0.17,0.87]

bias1 = 2.0
bias2 = 3.0
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3]+bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3]+bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3]+bias3]

print(output)

[4.8, 1.21, 2.385]


Let us simplify the code above. Let's see how NN sees this

In [ ]:
inputs = [1.0,2.0,3.0,2.5]

weights = [[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

biases = [2.0,3.0,0.5]

'''
layer_outputs = [] #output of current layer
for neuron_weights, neuron_biases in zip(weights,biases):
  neuron_output = 0
  for n_input,weight in zip(inputs,neuron_weights):
    neuron_output += n_input*weight
  neuron_output += neuron_biases #takes place outside loop since it is added to the product after loop not to each element
  layer_outputs.append(neuron_output)

print(layer_outputs)
'''



[4.8, 1.21, 2.385]


Trying to understand this in terms of dot product

Lesson 3

In [ ]:
inputs = [1.0,2.0,3.0,2.5]   #vector

weights = [[0.2,0.8,-0.5,1],   #matrix of vectors
           [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]]

biases = [2.0,3.0,0.5]  #vector

In [ ]:
import numpy as np

inputs = [1.0,2.0,3.0,2.5]
weights = [0.2,0.8,-0.5,1]
bias = 2

outcome = np.dot(inputs,weights) + bias

In [ ]:
print(outcome)

4.8


Layers, Batches and onbject

In [ ]:
import numpy as np

inputs = [[1.0,2.0,3.0,2.5],
          [2.0,5.0,-1.0,2],
          [-1.5,2.7,3.3,-0.8]]

weights = [[0.2,0.8,-0.5,1],   #matrix of vectors
           [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]]



biases = [2.0,3.0,0.5]

output = np.dot(inputs,np.array(weights).T) + biases   #the reason why we needed to do transpose is written in the copy ( Matrix multiplication)

print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


###Lesson 4

In [4]:
import numpy as np

inputs = [[1.0,2.0,3.0,2.5],
          [2.0,5.0,-1.0,2],
          [-1.5,2.7,3.3,-0.8]]

weights1 = [[0.2,0.8,-0.5,1],   #matrix of vectors
           [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]]

biases1 = [2.0,3.0,0.5]


weights2 = [[0.1,-0.14,0.5],   #matrix of vectors
           [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]]

biases2 = [-1,-2,-0.5]


layer1_output = np.dot(inputs,np.array(weights1).T) + biases1

layer2_output = np.dot(layer1_output,np.array(weights2).T) + biases2

print(layer2_output)


[[ 0.5031  -5.04185 -2.03875]
 [ 0.2434  -6.7332  -5.7633 ]
 [-0.99314 -2.58746 -0.35655]]
