<a href="https://colab.research.google.com/github/srijit43/Machine-Learning-Lessions/blob/main/Neural_Network_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

inputs = [[1.0,2.0,3.0,2.5],
          [2.0,5.0,-1.0,2],
          [-1.5,2.7,3.3,-0.8]]

###Use random to randomize a set of weights

In [ ]:
np.random.seed()

The input denotes an actual set of inputs in the Neural Network

In [9]:
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = .10 * np.random.randn(n_inputs,n_neurons)  #shape that we want to pass, size of input coming in? and how many neurons we want to have? 0.1 to keep it under 1 ( Also we dont have to transpose in this case)
    self.biases = np.zeros((1,n_neurons))  #shape preserved 1 row, 3 columns (as per neuron count)

  def forward(self,inputs):
    self.output = np.dot(inputs,np.array(self.weights)) + self.biases

layer1 = Layer_Dense(4,5)  #size of inputs and number of neurons  ( features in each smaple, ie how many features 1,2,3,4 and any number of neurons which is shape of output)
layer2 = Layer_Dense(5,2)  #input is of size 5 because here the input is layer1


layer1.forward(inputs)
print(layer1.output)

layer2.forward(layer1.output)  #layer 1 is input for layer 2
print(layer2.output)

[[-0.04164099 -0.14550912 -0.48884342 -0.07315209 -0.37310019]
 [ 0.08735674 -0.15222929 -1.49848134 -0.09232612 -0.23688745]
 [ 0.27649158 -0.49601174 -0.28761334 -0.31801989  0.23528002]]
[[ 0.07075274  0.05540222]
 [ 0.14567413  0.07317174]
 [ 0.00818117 -0.03326159]]
